# Generated by Django 3.1.7 on 2021-04-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrador',
            name='observacion',
            field=models.CharField(max_length=90),
        ),
    ]
