# Generated by Django 3.1.7 on 2021-03-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('estado', models.CharField(max_length=10)),
                ('costo', models.FloatField()),
                ('descripcion', models.TextField()),
                ('fkTipo', models.CharField(max_length=30)),
            ],
        ),
    ]
